
Import-Module JAMS

Function Write-Banner{

[CmdletBinding(SupportsShouldProcess=$True)]
	Param(
		[Parameter(Mandatory=$True)]
		[String]
		[ValidateScript({if ($_.Length -gt 20) {Throw('Input to long')} else {$true}})]
		$Object,
		[Parameter(Mandatory=$False)]
		[System.ConsoleColor]
		$ForegroundColor = (Get-Host).UI.RawUI.Foregroundcolor,
		[Parameter(Mandatory=$False)]
		[System.ConsoleColor]
		$BackgroundColor = (Get-Host).UI.RawUI.Backgroundcolor
)
Begin
	{
		$outputarray = @("","","","","","","","","")
		$Alphabet = New-Object system.collections.hashtable
		$Alphabet." " = @('        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ')
		$Alphabet."!" = @('   !!   ',
				'   !!   ',
				'   !!   ',
				'   !!   ',
				'   !!   ',
				'        ',
				'        ',
				'   !!   ',
				'   !!   ')
		$Alphabet."""" = @('  "  "  ',
				'  "  "  ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ')
		$Alphabet."#" = @('        ',
				'   # #  ',
				'   # #  ',
				' #######',
				'   # #  ',
				' #######',
				'   # #  ',
				'   # #  ',
				'        ')
		$Alphabet."$" = @('    $   ',
				'  $$$$$ ',
				' $  $  $',
				' $  $   ',
				'  $$$$$ ',
				'    $  $',
				' $  $  $',
				'  $$$$$ ',
				'    $   ')
		$Alphabet."%" = @('  %     ',
				' % %   %',
				'  %   % ',
				'     %  ',
				'    %   ',
				'   %    ',
				'  %   % ',
				' %   % %',
				'      % ')
		$Alphabet."'" = @("    ''  ",
				"    ''  ",
				"    '   ",
				"   '    ",
				"        ",
				"        ",
				"        ",
				"        ",
				"        ");
		$Alphabet."(" = @('     (  ',
				'    (   ',
				'   (    ',
				'   (    ',
				'   (    ',
				'   (    ',
				'   (    ',
				'    (   ',
				'     (  ')
		$Alphabet.")" = @('   )    ',
				'    )   ',
				'     )  ',
				'     )  ',
				'     )  ',
				'     )  ',
				'     )  ',
				'    )   ',
				'   )    ')
		$Alphabet."*" = @('        ',
				'    *   ',
				' *  *  *',
				'  * * * ',
				'   ***  ',
				'  * * * ',
				' *  *  *',
				'    *   ',
				'        ')
		$Alphabet."+" = @('        ',
				'    +   ',
				'    +   ',
				'    +   ',
				' +++++++',
				'    +   ',
				'    +   ',
				'    +   ',
				'        ')
		$Alphabet."," = @('        ',
				'        ',
				'        ',
				'        ',
				'   ,,   ',
				'   ,,   ',
				'   ,    ',
				'  ,     ',
				'        ')
		$Alphabet."-" = @('        ',
				'        ',
				'        ',
				'        ',
				' -------',
				'        ',
				'        ',
				'        ',
				'        ')
		$Alphabet."." = @('        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'   ..   ',
				'   ..   ')
		$Alphabet."/" = @('        ',
				'       /',
				'      / ',
				'     /  ',
				'    /   ',
				'   /    ',
				'  /     ',
				' /      ',
				'        ')
		$Alphabet."0" = @('  00000 ',
				' 0     0',
				' 0    00',
				' 0   0 0',
				' 0  0  0',
				' 0 0   0',
				' 00    0',
				' 0     0',
				'  00000 ')
		$Alphabet."1" = @('    1   ',
				'   11   ',
				'  1 1   ',
				'    1   ',
				'    1   ',
				'    1   ',
				'    1   ',
				'    1   ',
				'  11111 ')
		$Alphabet."2" = @('  22222 ',
				' 2     2',
				'       2',
				'      2 ',
				'   222  ',
				'  2     ',
				' 2      ',
				' 2      ',
				' 2222222')
		$Alphabet."3" = @('  33333 ',
				' 3     3',
				'       3',
				'       3',
				'   3333 ',
				'       3',
				'       3',
				' 3     3',
				'  33333 ')
		$Alphabet."4" = @('      4 ',
				'     44 ',
				'    4 4 ',
				'   4  4 ',
				'  4   4 ',
				' 4    4 ',
				' 4444444',
				'      4 ',
				'      4 ')
		$Alphabet."5" = @(' 5555555',
				' 5      ',
				' 5      ',
				' 55555  ',
				'      5 ',
				'       5',
				'       5',
				' 5    5 ',
				'  5555  ')
		$Alphabet."6" = @('   6666 ',
				'  6     ',
				' 6      ',
				' 6      ',
				' 6 6666 ',
				' 66    6',
				' 6     6',
				' 6     6',
				'  66666 ')
		$Alphabet."7" = @(' 7777777',
				' 7     7',
				'      7 ',
				'     7  ',
				'    7   ',
				'   7    ',
				'   7    ',
				'   7    ',
				'   7    ')
		$Alphabet."8" = @('  88888 ',
				' 8     8',
				' 8     8',
				' 8     8',
				'  88888 ',
				' 8     8',
				' 8     8',
				' 8     8',
				'  88888 ')
		$Alphabet."9" = @('  99999 ',
				' 9     9',
				' 9     9',
				' 9     9',
				'  999999',
				'       9',
				'       9',
				' 9     9',
				'  9999  ')
		$Alphabet.":" = @('        ',
				'        ',
				'        ',
				'   ::   ',
				'   ::   ',
				'        ',
				'        ',
				'   ::   ',
				'   ::   ')
		$Alphabet.";" = @('   ;;   ',
				'   ;;   ',
				'        ',
				'        ',
				'   ;;   ',
				'   ;;   ',
				'   ;    ',
				'  ;     ',
				'        ')
		$Alphabet."=" = @('        ',
				'        ',
				'        ',
				' =======',
				'        ',
				' =======',
				'        ',
				'        ',
				'        ')
		$Alphabet."?" = @('   ???? ',
				'  ?    ?',
				'  ?    ?',
				'       ?',
				'     ?? ',
				'    ?   ',
				'    ?   ',
				'        ',
				'    ?   ')
		$Alphabet."@" = @('   @@@@ ',
				'  @    @',
				' @  @@ @',
				' @ @ @ @',
				' @ @ @ @',
				' @ @@@@ ',
				' @      ',
				'  @    @',
				'   @@@@ ')
		$Alphabet."A" = @('   AAA  ',
				'  A   A ',
				' A     A',
				' A     A',
				' AAAAAAA',
				' A     A',
				' A     A',
				' A     A',
				' A     A')
		$Alphabet."B" = @(' BBBBBB ',
				'  B    B',
				'  B    B',
				'  B    B',
				'  BBBBB ',
				'  B    B',
				'  B    B',
				'  B    B',
				' BBBBBB ')
		$Alphabet."C" = @('   CCCC ',
				'  C    C',
				' C      ',
				' C      ',
				' C      ',
				' C      ',
				' C      ',
				'  C    C',
				'   CCCC ')
		$Alphabet."D" = @(' DDDDD  ',
				'  D   D ',
				'  D    D',
				'  D    D',
				'  D    D',
				'  D    D',
				'  D    D',
				'  D   D ',
				' DDDDD  ')
		$Alphabet."E" = @(' EEEEEEE',
				' E      ',
				' E      ',
				' E      ',
				' EEEEEE ',
				' E      ',
				' E      ',
				' E      ',
				' EEEEEEE')
		$Alphabet."F" = @(' FFFFFFF',
				' F      ',
				' F      ',
				' F      ',
				' FFFFFF ',
				' F      ',
				' F      ',
				' F      ',
				' F      ')
		$Alphabet."G" = @('   GGGG ',
				'  G    G',
				' G      ',
				' G      ',
				' G      ',
				' G  GGGG',
				' G     G',
				'  G    G',
				'   GGGG ')
		$Alphabet."H" = @(' H     H',
				' H     H',
				' H     H',
				' H     H',
				' HHHHHHH',
				' H     H',
				' H     H',
				' H     H',
				' H     H')
		$Alphabet."I" = @('  IIIII ',
				'    I   ',
				'    I   ',
				'    I   ',
				'    I   ',
				'    I   ',
				'    I   ',
				'    I   ',
				'  IIIII ')
		$Alphabet."J" = @('   JJJJJ',
				'     J  ',
				'     J  ',
				'     J  ',
				'     J  ',
				'     J  ',
				'     J  ',
				' J   J  ',
				'  JJJ   ')
		$Alphabet."K" = @(' K     K',
				' K    K ',
				' K   K  ',
				' K  K   ',
				' K K    ',
				' KK K   ',
				' K   K  ',
				' K    K ',
				' K     K')
		$Alphabet."L" = @(' L      ',
				' L      ',
				' L      ',
				' L      ',
				' L      ',
				' L      ',
				' L      ',
				' L      ',
				' LLLLLLL')
		$Alphabet."M" = @(' M     M',
				' MM   MM',
				' M M M M',
				' M  M  M',
				' M     M',
				' M     M',
				' M     M',
				' M     M',
				' M     M')
		$Alphabet."N" = @(' N     N',
				' NN    N',
				' N N   N',
				' N  N  N',
				' N   N N',
				' N    NN',
				' N     N',
				' N     N',
				' N     N')
		$Alphabet."O" = @('   OOO  ',
				'  O   O ',
				' O     O',
				' O     O',
				' O     O',
				' O     O',
				' O     O',
				'  O   O ',
				'   OOO  ')
		$Alphabet."P" = @(' PPPPPP ',
				' P     P',
				' P     P',
				' P     P',
				' PPPPPP ',
				' P      ',
				' P      ',
				' P      ',
				' P      ')
		$Alphabet."Q" = @('   QQQ  ',
				'  Q   Q ',
				' Q     Q',
				' Q     Q',
				' Q     Q',
				' Q  Q  Q',
				' Q   Q Q',
				'  Q   Q ',
				'   QQQ Q')
		$Alphabet."R" = @(' RRRRRR ',
				' R     R',
				' R     R',
				' R     R',
				' RRRRRR ',
				' R  R   ',
				' R   R  ',
				' R    R ',
				' R     R')
		$Alphabet."S" = @('  SSSSS ',
				' S     S',
				' S      ',
				' S      ',
				'  SSSSS ',
				'       S',
				'       S',
				' S     S',
				'  SSSSS ')
		$Alphabet."T" = @(' TTTTTTT',
				'    T   ',
				'    T   ',
				'    T   ',
				'    T   ',
				'    T   ',
				'    T   ',
				'    T   ',
				'    T   ')
		$Alphabet."U" = @(' U     U',
				' U     U',
				' U     U',
				' U     U',
				' U     U',
				' U     U',
				' U     U',
				' U     U',
				'  UUUUU ')
		$Alphabet."V" = @(' V     V',
				' V     V',
				' V     V',
				'  V   V ',
				'  V   V ',
				'   V V  ',
				'   V V  ',
				'    V   ',
				'    V   ')
		$Alphabet."W" = @(' W     W',
				' W     W',
				' W     W',
				' W     W',
				' W  W  W',
				' W  W  W',
				' W W W W',
				' WW   WW',
				' W     W')
		$Alphabet."X" = @(' X     X',
				' X     X',
				'  X   X ',
				'   X X  ',
				'    X   ',
				'   X X  ',
				'  X   X ',
				' X     X',
				' X     X')
		$Alphabet."Y" = @(' Y     Y',
				' Y     Y',
				'  Y   Y ',
				'   Y Y  ',
				'    Y   ',
				'    Y   ',
				'    Y   ',
				'    Y   ',
				'    Y   ')
		$Alphabet."Z" = @(' ZZZZZZZ',
				'       Z',
				'      Z ',
				'     Z  ',
				'    Z   ',
				'   Z    ',
				'  Z     ',
				' Z      ',
				' ZZZZZZZ')
		$Alphabet."Å" = @('   ÅÅÅ  ',
				'  Å   Å ',
				'   ÅÅÅ  ',
				'  Å   Å ',
				' Å     Å',
				' ÅÅÅÅÅÅÅ',
				' Å     Å',
				' Å     Å',
				' Å     Å')
		$Alphabet."Ä" = @(' Ä     Ä',
				'   ÄÄÄ  ',
				'  Ä   Ä ',
				' Ä     Ä',
				' Ä     Ä',
				' ÄÄÄÄÄÄÄ',
				' Ä     Ä',
				' Ä     Ä',
				' Ä     Ä')
		$Alphabet."Ö" = @(' Ö     Ö',
				'   ÖÖÖ  ',
				'  Ö   Ö ',
				' Ö     Ö',
				' Ö     Ö',
				' Ö     Ö',
				' Ö     Ö',
				'  Ö   Ö ',
				'   ÖÖÖ  ')
		$Alphabet."[" = @('  [[[[  ',
				'  [     ',
				'  [     ',
				'  [     ',
				'  [     ',
				'  [     ',
				'  [     ',
				'  [     ',
				'  [[[[  ')
		$Alphabet."\" = @('        ',
				' \      ',
				'  \     ',
				'   \    ',
				'    \   ',
				'     \  ',
				'      \ ',
				'       \',
				'        ')
		$Alphabet."]" = @('   ]]]] ',
				'      ] ',
				'      ] ',
				'      ] ',
				'      ] ',
				'      ] ',
				'      ] ',
				'      ] ',
				'   ]]]] ')
		$Alphabet." " = @('        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ')
<#
		$Alphabet."`" = @('   ``   ',
				'   ``   ',
				'    `   ',
				'     `  ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ')
#>
		$Alphabet."a" = @('        ',
				'        ',
				'        ',
				'  aaaa  ',
				'      a ',
				'  aaaaa ',
				' a     a',
				' a    aa',
				'  aaaa a')
		$Alphabet."b" = @(' b      ',
				' b      ',
				' b      ',
				' b bbb  ',
				' bb   b ',
				' b     b',
				' b     b',
				' bb   b ',
				' b bbb  ')
		$Alphabet."c" = @('        ',
				'        ',
				'        ',
				'  cccc  ',
				' c    c ',
				' c      ',
				' c      ',
				' c    c ',
				'  cccc  ')
		$Alphabet."d" = @('      d ',
				'      d ',
				'      d ',
				'  ddd d ',
				' d   dd ',
				' d    d ',
				' d    d ',
				' d   dd ',
				'  ddd d ')
		$Alphabet."e" = @('        ',
				'        ',
				'        ',
				'  eeee  ',
				' e    e ',
				' eeeeee ',
				' e      ',
				' e    e ',
				'  eeee  ')
		$Alphabet."f" = @('    ff  ',
				'   f  f ',
				'   f    ',
				'   f    ',
				' fffff  ',
				'   f    ',
				'   f    ',
				'   f    ',
				'   f    ')
		$Alphabet."g" = @('  ggg g ',
				' g   gg ',
				' g    g ',
				' g    g ',
				' g   gg ',
				'  ggg g ',
				'      g ',
				' g    g ',
				'  gggg  ')
		$Alphabet."h" = @(' h      ',
				' h      ',
				' h      ',
				' h hhh  ',
				' hh   h ',
				' h    h ',
				' h    h ',
				' h    h ',
				' h    h ')
		$Alphabet."i" = @('        ',
				'    i   ',
				'        ',
				'   ii   ',
				'    i   ',
				'    i   ',
				'    i   ',
				'    i   ',
				'   iii  ')
		$Alphabet."j" = @('     jj ',
				'      j ',
				'      j ',
				'      j ',
				'      j ',
				'      j ',
				'      j ',
				'  j   j ',
				'   jjj  ')
		$Alphabet."k" = @(' k      ',
				' k      ',
				' k      ',
				' k   k  ',
				' k  k   ',
				' k k    ',
				' kk k   ',
				' k   k  ',
				' k    k ')
		$Alphabet."l" = @('   ll   ',
				'    l   ',
				'    l   ',
				'    l   ',
				'    l   ',
				'    l   ',
				'    l   ',
				'    l   ',
				'   lll  ')
		$Alphabet."m" = @('        ',
				'        ',
				'        ',
				' m m mm ',
				' mm m  m',
				' m  m  m',
				' m  m  m',
				' m  m  m',
				' m  m  m')
		$Alphabet."n" = @('        ',
				'        ',
				'        ',
				' n nnn  ',
				' nn   n ',
				' n    n ',
				' n    n ',
				' n    n ',
				' n    n ')
		$Alphabet."o" = @('        ',
				'        ',
				'        ',
				'  oooo  ',
				' o    o ',
				' o    o ',
				' o    o ',
				' o    o ',
				'  oooo  ')
		$Alphabet."p" = @(' p ppp  ',
				' pp   p ',
				' p    p ',
				' p    p ',
				' pp   p ',
				' p ppp  ',
				' p      ',
				' p      ',
				' p      ')
		$Alphabet."q" = @('  qqq q ',
				' q   qq ',
				' q    q ',
				' q    q ',
				' q   qq ',
				'  qqq q ',
				'      q ',
				'      q ',
				'      q ')
		$Alphabet."r" = @('        ',
				'        ',
				'        ',
				' r rrr  ',
				' rr   r ',
				' r      ',
				' r      ',
				' r      ',
				' r      ')
		$Alphabet."s" = @('        ',
				'        ',
				'        ',
				'  ssss  ',
				' s    s ',
				'  ss    ',
				'    ss  ',
				' s    s ',
				'  ssss  ')
		$Alphabet."t" = @('        ',
				'   t    ',
				'   t    ',
				' ttttt  ',
				'   t    ',
				'   t    ',
				'   t    ',
				'   t  t ',
				'    tt  ')
		$Alphabet."u" = @('        ',
				'        ',
				'        ',
				' u    u ',
				' u    u ',
				' u    u ',
				' u    u ',
				' u   uu ',
				'  uuu u ')
		$Alphabet."v" = @('        ',
				'        ',
				'        ',
				' v     v',
				' v     v',
				' v     v',
				'  v   v ',
				'   v v  ',
				'    v   ')
		$Alphabet."w" = @('        ',
				'        ',
				'        ',
				' w     w',
				' w  w  w',
				' w  w  w',
				' w  w  w',
				' w  w  w',
				'  ww ww ')
		$Alphabet."x" = @('        ',
				'        ',
				'        ',
				' x    x ',
				'  x  x  ',
				'   xx   ',
				'   xx   ',
				'  x  x  ',
				' x    x ')
		$Alphabet."y" = @(' y    y ',
				' y    y ',
				' y    y ',
				' y    y ',
				' y   yy ',
				'  yyy y ',
				'      y ',
				' y    y ',
				'  yyyy  ')
		$Alphabet."z" = @('        ',
				'        ',
				'        ',
				' zzzzzz ',
				'     z  ',
				'    z   ',
				'   z    ',
				'  z     ',
				' zzzzzz ')
		$Alphabet."}" = @('    }}  ',
				'   }    ',
				'   }    ',
				'   }    ',
				'  }     ',
				'   }    ',
				'   }    ',
				'   }    ',
				'    }}  ')
		$Alphabet."|" = @('    |   ',
				'    |   ',
				'    |   ',
				'    |   ',
				'    |   ',
				'    |   ',
				'    |   ',
				'    |   ',
				'    |   ')
		$Alphabet."}" = @('   }}   ',
				'     }  ',
				'     }  ',
				'     }  ',
				'      } ',
				'     }  ',
				'     }  ',
				'     }  ',
				'   }}   ')
		$Alphabet."~" = @('  ~~    ',
				' ~  ~  ~',
				'     ~~ ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ')
	}
Process
	{
		ForEach($char in $Object[0..($Object.length-1)])
		{
			if ($Alphabet[[string]$char] -ne $Null)
			{
				ForEach($i in 0..8)
				{
					$outputarray[$i] += $Alphabet[[string]$char][$i]
				}
			}
		}

		ForEach($i in 0..8)
		{
			Write-Host -Object $outputarray[$i] -Foregroundcolor:$Foregroundcolor -Backgroundcolor:$Backgroundcolor
		}
	}
}


$RLOGS=@()
CD JAMS::localhost\SAMC_specalized_jobs\SERVER_REBOOTS\TEMP
get-childitem -include RBLOG_* -name | foreach{
     
   $wa=Get-JAMSVariable -name $_ -ValueOnly
   $wwa=$wa.split(" ")
   write-host "============================================================================================================================================================"
   write-host "============================================================================================================================================================"
   write-host "============================================================================================================================================================"
   write-host ""
   write-host ""
   $stng=" JAMS ENTRY " +$wwa[0]
   Write-Banner $stng
   write-host ""
   write-host ""
   write-host "============================================================================================================================================================"
   write-host "============================================================================================================================================================"
   write-host "============================================================================================================================================================"
   $RLOGS+=($wwa[0])
   Get-Content ($wwa[1]).ToString()
}

# OK, so I'm done.. so now remove all the items

write-host "clean up"
Set-Location JAMS::localhost\SAMC_specalized_jobs\SERVER_REBOOTS\TEMP
$RLOGS | foreach{
   $VARNAME="RBLOG_" +$_
   Remove-Item $VARNAME
}






