#!/usr/bin/ksh
set -x
cd /tmp
<<COMMAND>>
<<COMMAND1>>
<<COMMAND2>>
<<COMMAND3>>
<<COMMAND4>>
<<COMMAND5>>
<<COMMAND6>>
<<COMMAND7>>
<<COMMAND8>>
<<COMMAND9>>
<<COMMANDA>>
<<COMMANDB>>
<<COMMANDC>>
<<COMMANDD>>
<<COMMANDE>>
<<COMMANDF>>



# again, you guessed it... here's the Parameters for this JOB

Type           Prompt                                          Parameter Name
     Text                                                      COMMAND
     Text                                                      COMMAND1
       .                                                           .
       .                                                           .
     Text                                                      COMMANDF
